### PR TITLE
Adding Support For SSL Connections To Elasticsearch Servers

### PR DESCRIPTION
**Pull request by mickdelaney**
I've added the ability to add a 'Scheme' connection string property which will then amend the URL for example, setting Scheme=https means it will use SSL. 
It will default to http if nothing is provided. 
I need this because I'm using https://found.no/ for logging. 
Let me know if i'm missing anything. 
Regards

### CODE REVIEW

**Comment by mickdelaney** [comment]
Is there anything you'd like from me with regards to this pull request??

**Comment by jptoto** [comment]
@mickdelaney Sorry about the delay! Been a hectic two weeks here. This PR is a great idea. I didn't realize the 3rd party ES providers required basic auth but of course, that makes sense. Taking a look right now.

**Comment by jptoto** [comment]
@mickdelaney would you mind pulling in the latest master? @jc74 made some updates and there are a few conflicts. I'd appreciate it. Thx!

**Comment by mickdelaney** [comment]
This seems to have done it. i just tested against found.no with SSL & user/password & it worked fine.

**Pull request merged**
