### PR TITLE
Fixed issue when serializing exception objects to JSON.

### PR DESCRIPTION
**Pull request by ttingen**
Fix for Issue #39 

Added a JsonSerializableException class and 2 integration tests to ensure they are logged to Elasticsearch.

### CODE REVIEW

**Comment by jptoto** [comment]
Fiddling with this this morning. Thanks for the PR!  I still seem to get the https://github.com/jptoto/log4net.ElasticSearch/issues/39 issue, however. I'm duplicating that issue locally, using the divide by 0 trick, and using your branch, and it's still throwing a serialization exception and not logging anything to ES. I tried running log4net in debug and without and the result still seems to be the same.

**Comment by ttingen** [comment]
Hmm, it's logging the exceptions to ES for me. I added a Divide by 0 test and it passes as well. Can you post the test that you added so I can try it locally?

**Comment by jptoto** [comment]
@ttingen I could definitely be doing something wrong. Here's what I tested it with, a basic Console.exe app.

https://gist.github.com/jptoto/fa22ffcb351966711447

Also including my app.config for debugging because I was still getting the serialization errors there. Curious if you see this on your side.

**Comment by ttingen** [comment]
I see what I had different in my test now. I logged the error with:

```
_log.Error("An exception occurred.", ex);
```

Where you were calling it like:

```
_log.Error(ex);
```

When logging the error using the second method, the loggingEvent.MessageObject is used for the exception instead of the loggingEvent.ExceptionObject.

I updated the logEvent construction to handle this scenario, it should pass your test now.

**Comment by jptoto** [comment]
Beautiful. Thank you!

**Pull request merged**
