### PR TITLE
update to TargetFrameworks  net40;net45;netstandard2.0

### PR DESCRIPTION
**Pull request by maikebing**

### CODE REVIEW

**Comment by maikebing** [comment]
@jptoto  Do you have time to review the code? Do I need to explain something to this PR?

**Comment by jptoto** [comment]
@maikebing Hey thanks for the PR! I will try to look at this tonight. Getting .net core support in soon was on my roadmap but I wasn't able to address it yet.

**Comment by jptoto** [comment]
@maikebing I've been taking a look at this. Nice work! I have a few questions. Admittedly, I haven't gotten up to speed on the new netstandard build process. The psake build does not work now. Is that not needed? I prefer to have a command line build process for automation. I see the builds work ok when I generate them from visual studio but we're going to need to maintain the command line build process for continuous integration platforms, automatic package builds, etc.

**Comment by maikebing** [comment]
@jptoto   I'm afraid I have to tell you the bad news, I don't know how to use Psake,I'm very, very sorry.

**Comment by jptoto** [comment]
@maikebing No worries! You've done some great work here. It may take me a bit of time but I will take this work and incorporate some changes so it's consistent with the previous build methods. You've given me a lot to start with so that I can complete it to add netstandard support which I had been putting off anyway. Thank you!

**Comment by jptoto** [comment]
Added netstandard20 support via https://github.com/jptoto/log4net.ElasticSearch/pull/98 Thank you for this PR!

**Pull request closed without merging**
