### PR TITLE
Fix for #42 - makes port optional in connectionString

### PR DESCRIPTION
**Pull request by aateeque**

### CODE REVIEW

**Comment by jptoto** [comment]
Thank you for the PR! Sorry for the delay.

**Comment by aateeque** [comment]
No problem...how long before this is released?

**Comment by jptoto** [comment]
@aateeque it's already on Nuget, version 2.2.0

**Comment by aateeque** [comment]
Yeah, just seen, thanks!!

**Comment by jptoto** [comment]
Thanks again for the PR and tests!

**Pull request merged**
